course/urls.py
from django.conf.urls import url
from . import views

app_name = 'course'
urlpatterns = [
    url(r'^join/(?P<group_id>[0-9]+)/$', views.joingroup, name='joingroup'),
    url(r'^leave/(?P<group_id>[0-9]+)/$', views.leavegroup, name='leavegroup'),
    url(r'(?P<group_id>[0-9]+)/$', views.index, name='index'),
]

meeting/urls.py
from django.conf.urls import url
from . import views

app_name = 'meeting'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^agenda/list/(?P<room_id>[0-9]+)/$', views.agenda_list, name='agenda_list'),
    url(r'^agenda/add/(?P<room_id>[0-9]+)/$', views.agenda_add, name='agenda_add'),
    url(r'^agenda/view/(?P<agenda_id>[0-9]+)/$', views.agenda_view, name='agenda_view'),
    url(r'^agenda/del/(?P<agenda_id>[0-9]+)/$', views.agenda_del, name='agenda_del'),
]

meeting/models.py
from django.db import models
import datetime

class MeetingRoom(models.Model):
    room_no = models.CharField(max_length=15, verbose_name="房间号")
    info = models.CharField(max_length=200, blank=True, verbose_name="描述")

    class Meta:
        verbose_name="会议室"
        verbose_name_plural="会议室"

    def get_agenda(self):
        return self.agenda.all()

    # to check if the agenda is without conflict
    def isOK(self, day, start, end):
        return True


class RoomAgenda(models.Model):
    room = models.ForeignKey(MeetingRoom, on_delete=models.CASCADE, related_name='agenda')
    title = models.CharField(max_length=200)
    userid = models.CharField(max_length=12)
    username = models.CharField(max_length=40)
    repeat = models.IntegerField(default=0)
    date = models.DateField(default='2018-01-01')
    week = models.IntegerField(default=-1)
    start_time = models.TimeField(default='00:00')
    end_time = models.TimeField(default='00:00')

    def collide_time(self, other):
        if ((self.start_time < other.end_time) and (self.start_time > other.start_time)):
            return True
        if ((self.end_time > other.start_time) and (self.end_time < other.end_time)):
            return True
        return False

    def collide(self):
        today = datetime.date.today()
        all_agenda = RoomAgenda.objects.filter(room=self.room,date__gte=today)
        if self.repeat == 1:
            for a in all_agenda.filter(week=self.week,repeat=1):
                if self.collide_time(a):
                    return True
            for a in all_agenda.filter(date__lte=self.date,week=self.week,repeat=0):
                if self.collide_time(a):
                    return True
        else:
            for a in all_agenda.filter(date=self.date,repeat=0):
                if self.collide_time(a):
                    return True
            for a in all_agenda.filter(date__gte=self.date,week=self.week,repeat=1):
                if self.collide_time(a):
                    return True
        return False

meeting/forms.py
from django import forms
import datetime
from .models import RoomAgenda, MeetingRoom

class AgendaForm(forms.Form):
    repeatable = forms.ChoiceField(
        required=True,
        label="日程类型",
        error_messages={'required': "日程类型必须选择"},
        choices=((1, "固定日期"), (2, "每周重复")),
        widget=forms.RadioSelect,
    )

    date = forms.DateField(
        required=False,
        label="日期",
        initial=datetime.date.today,
        widget=forms.SelectDateWidget,
    )

    week = forms.ChoiceField(
        required=False,
        label="星期",
        choices=((0, "周一"), (1, "周二"), (2, "周三"), (3, "周四"),
            (4, "周五"), (5, "周六"), (6, "周日")),
    )

    start = forms.TimeField(
        required=True,
        label="起始时间",
    )

    end = forms.TimeField(
        required=True,
        label="结束时间",
    )

    note = forms.CharField(
        required=True,
        label="事由",
        initial="",
    )

    def clean(self):
        super().clean()
        if (not self.is_valid()):
            return
        s = self.cleaned_data.get('start')
        e = self.cleaned_data.get('end')
        if (s >= e):
            raise forms.ValidationError("起始时间要早于结束时间")
        d = self.cleaned_data.get('date')
        if (d < datetime.date.today()):
            raise forms.ValidationError("日期不能在过去")

meeting/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from .models import MeetingRoom, RoomAgenda
from .forms import AgendaForm
from django.urls import reverse
import datetime

def index(request):
    rooms = MeetingRoom.objects.all()
    if (rooms.count() == 0):
        raise Http404("没有定义会议室")
    if (rooms.count() > 1):
        return render(request, 'meeting/room_index.html', {'rooms': rooms})
    return HttpResponseRedirect(reverse('meeting:agenda_list', args=(rooms.first().id,)))

def agenda_add(request, room_id):
    room = get_object_or_404(MeetingRoom, pk=room_id)
    errors = []
    if (not request.session.has_key('schoolid')) or request.user.username != request.session['schoolid']:
        errors = ["你没有增加日程的权限"]
    if request.method == 'POST':
        form = AgendaForm(request.POST)
        if form.is_valid():
            agenda = RoomAgenda(room=room)
            agenda.title = form.cleaned_data['note']
            agenda.start_time = form.cleaned_data['start']
            agenda.end_time = form.cleaned_data['end']
            agenda.userid = request.session['schoolid']
            agenda.week = form.cleaned_data['week']
            agenda.date = form.cleaned_data['date']
            agenda.username = request.session['realname']
            if form.cleaned_data['repeatable'] == '2':
                agenda.repeat = 1
            else:
                agenda.repeat = 0
                agenda.week = agenda.date.weekday() # make sure the week is right
            if agenda.collide():
                errors= errors + ["与其它日程存在冲突，请检查"]
            if agenda.repeat == 1:
                if (agenda.date - datetime.date.today()).days < 7:
                    errors = errors + ["每周重复日程请设定合适的截止日期"]
            if len(errors) == 0:
                agenda.save()
                return HttpResponseRedirect(reverse('meeting:agenda_list', args=(room.id,)))
    else:
        form = AgendaForm()
    return render(request, 'meeting/agenda_add.html', {'form': form, 'errors':errors})

def agenda_list(request, room_id):
    room = get_object_or_404(MeetingRoom, pk=room_id)
    td = datetime.date.today()
    td = td - datetime.timedelta(days=td.weekday()) # whole week
    agendas = RoomAgenda.objects.filter(room=room,date__gte=td)
    for a in agendas:
        a.view = ""
        if (a.repeat == 0) and (a.date > td + datetime.timedelta(days=6)):
            continue
        a.view = a.view + "left: %dpx;" % (a.week * 80 + 50)
        k = (a.start_time.hour - 5) * 40 + (a.start_time.minute / 6 * 4) - 5
        a.view = a.view + "top: %dpx;" % k
        k = (a.end_time.hour - a.start_time.hour) * 40 + (a.end_time.minute - a.start_time.minute) / 6 * 4
        a.view = a.view + "height: %dpx;" % k
    return render(request, 'meeting/agenda_list.html', {'agendas': agendas, 'room_id': room_id})

def agenda_view(request, agenda_id):
    agenda = get_object_or_404(RoomAgenda, pk=agenda_id)
    return render(request, 'meeting/agenda_view.html', {'agenda': agenda})

def agenda_del(request, agenda_id):
    agenda = get_object_or_404(RoomAgenda, pk=agenda_id)
    room = agenda.room
    if (agenda.userid == request.session['schoolid']) or (request.user.is_superuser):
        agenda.delete()
    return HttpResponseRedirect(reverse('meeting:agenda_list', args=(room.id,)))

meeting/templates/meeting/agenda_add.html
{% extends "nav.html" %}

{% load bootstrap4 %}

{% bootstrap_messages %}

{% block subtitle %}日程列表{% endblock %}
{% block body_class %}functions{% endblock %}
{% block mainblk %}
<div class="row">
  <div class="col-md-5">
    {% for err in errors %}
    <div class="alert alert-danger" role="alert">
        <h4>{{ err }}</h4>
    </div>
    {% endfor %}
      <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">
       提交 
      </button>
    {% endbuttons %}
  </form>
  </div>
  <div class="col-md-5">
    <div class="alert alert-primary" role="alert">
       提示：固定时间的日程星期项被忽略
    </div>
    <div class="alert alert-primary" role="alert">
       提示：每周重复的日程日期项表示重复截止的日期，也就是设定日期之后的会议室不会被预订
    </div>
    <div class="alert alert-primary" role="alert">
       提示：起始时间和结束时间的格式是"HH:MM"，例如"11:30"表示11点30分
    </div>
    <div class="alert alert-primary" role="alert">
       提示：事由请简明扼要
    </div>
  </div>
</div>
{% endblock %}

meeting/templates/meeting/agenda_list.html
{% extends "nav.html" %}

{% load bootstrap4 %}

{% bootstrap_messages %}

{% block subtitle %}日程列表{% endblock %}
{% block body_class %}agenda{% endblock %}
{% block mainblk %}
<ul class="nav nav-tabs">
    <li class="nav-item"><a class="nav-link active" href="#aaa" data-toggle="tab">日程表</a></li>
    <li class="nav-item"><a class="nav-link" href="#bbb" data-toggle="tab">日程详细列表</a></li>
</ul>
<div class="tab-content" id="tabs">
  <div class="tab-pane" id="bbb">
  <div class="col-md-8">
      <table class="table table-bordered table-hover table-sm">
          <tr><th>事项</th><th>日期</th><th>操作</th></tr>
            {% for agenda in agendas %}
              <tr><td> {{ agenda.title }} </td><td>
                {% if agenda.repeat == 0 %} {{ agenda.date }} {% else %}
                  {% if agenda.week == 0 %}周一{% endif %}
                  {% if agenda.week == 1 %}周二{% endif %}
                  {% if agenda.week == 2 %}周三{% endif %}
                  {% if agenda.week == 3 %}周四{% endif %}
                  {% if agenda.week == 4 %}周五{% endif %}
                  {% if agenda.week == 5 %}周六{% endif %}
                  {% if agenda.week == 6 %}周日{% endif %}
                  （截止日期 {{ agenda.date }}）
                {% endif %}
                  </td>
                  <td><a href="{% url 'meeting:agenda_view' agenda.id %}">查看</a></td>
              </tr>
            {% endfor %}
      </table>
  </div>
  </div>
  <div class="tab-pane active" id="aaa">
  <div class="container p-0" style="position: relative;min-height:500px">
    <table class="table-sm table-bordered">
        <tr><th style="width:50px"></th><td class="cal-header">周一</td>
            <td class="cal-header">周二</td>
            <td class="cal-header">周三</td>
            <td class="cal-header">周四</td>
            <td class="cal-header">周五</td>
            <td class="cal-header">周六</td>
            <td class="cal-header">周日</td></tr>
        <tr><th class="cal-row">06:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">07:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">08:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">09:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">10:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">11:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">12:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">13:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">14:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">15:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">16:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">17:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">18:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">19:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">20:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">21:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">22:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">23:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        <tr><th class="cal-row">24:00</th><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
    </table>
    {% for agenda in agendas %}
    {% if agenda.view != '' %}
        <div class="calendar" style="position: absolute;{{ agenda.view }}">
            <a href="{% url 'meeting:agenda_view' agenda.id %}">{{agenda.title }}</a>
        </div>
    {% endif %}
    {% endfor %}
  </div>
  </div>
</div>
{% endblock %}
{% block sidebar %}
<li><a href="{% url 'meeting:agenda_add' room_id %}">增加新日程</a>
{% endblock %}

meeting/templates/meeting/agenda_view.html
{% extends "nav.html" %}

{% load bootstrap4 %}

{% bootstrap_messages %}

{% block subtitle %}日程详情{% endblock %}
{% block body_class %}agenda{% endblock %}
{% block mainblk %}
<div class="row">
  <div class="col-md-8">
      <table class="table table-bordered table-sm">
          <tr><th>事项</th><td> {{ agenda.title }} </td></tr>
          <tr><th>类型</th><td> {% if agenda.repeat == 1 %} 每周重复
                  {% if agenda.week == 0 %}（周一）{% endif %}
                  {% if agenda.week == 1 %}（周二）{% endif %}
                  {% if agenda.week == 2 %}（周三）{% endif %}
                  {% if agenda.week == 3 %}（周四）{% endif %}
                  {% if agenda.week == 4 %}（周五）{% endif %}
                  {% if agenda.week == 5 %}（周六）{% endif %}
                  {% if agenda.week == 6 %}（周日）{% endif %}
                  {% else %} 固定日期 {% endif %}
          <tr><th>{% if agenda.repeat == 1 %}截止{% endif %}日期</th><td> {{ agenda.date }} </td></tr>
          <tr><th>开始时间</th><td> {{ agenda.start_time }} </td>
          <tr><th>结束时间</th><td> {{ agenda.end_time}} </td>
          <tr><th>预订人</th><td> {{ agenda.username }} </td>
      </table>
      {% if user.is_superuser or request.session.schoolid == agenda.userid %}
         <a href="{% url 'meeting:agenda_del' agenda.id %}">删除</a>
      {% endif %}
  </div>
</div>
{% endblock %}

meeting/templates/meeting/room_index.html
{% extends "nav.html" %}

{% load wagtailcore_tags %}

{% block subtitle %}会议室列表{% endblock %}
{% block body_class %}functions{% endblock %}
{% block mainblk %}
    <h4 class="text-center">会议室列表</h4>
    {% for room in rooms %}
      {{ room.room_no }} , {{ room.info }} <br>
    {% endfor %}

{% endblock %}