course/urls.py
from django.conf.urls import url
from . import views

app_name = 'course'
urlpatterns = [
    url(r'^join/(?P<group_id>[0-9]+)/$', views.joingroup, name='joingroup'),
    url(r'^leave/(?P<group_id>[0-9]+)/$', views.leavegroup, name='leavegroup'),
    url(r'(?P<group_id>[0-9]+)/$', views.index, name='index'),
]

course/models.py
from django.db import models

from wagtail.core.models import Page, Orderable
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel, InlinePanel, TabbedInterface, ObjectList
from modelcluster.fields import ParentalKey
from wagtail.documents.edit_handlers import DocumentChooserPanel
from wagtail.search import index

class CourseIndexPage(Page):
    parent_page_types = ['home.HomePage']
    subpage_types = ['CoursePage']

    class Meta:
        verbose_name = "课程列表"

class CoursePage(Page):
    name = models.CharField(max_length=20, verbose_name="课程名")
    ename = models.CharField(max_length=100, verbose_name="英文名称")
    number = models.CharField(max_length=10, verbose_name="课程编号")
    teacher = models.CharField(max_length=20, verbose_name="授课教师")
    teaid = models.CharField(max_length=12, verbose_name="教师工资号")
    unit = models.IntegerField(default=0, verbose_name="学分")
    hours = models.IntegerField(default=0, verbose_name="课时")
    terms = models.CharField(max_length=20, verbose_name="授课学期")
    body = RichTextField(blank=True, verbose_name="课程大纲")

    search_fields = Page.search_fields + [
        index.SearchField('body'),
    ]

    content_panels = Page.content_panels + [
        FieldPanel('name'),
        FieldPanel('ename'),
        FieldPanel('number'),
        FieldPanel('teacher'),
        FieldPanel('teaid'),
        FieldPanel('unit'),
        FieldPanel('hours'),
        FieldPanel('terms'),
        FieldPanel('body', classname="full"),
    ]

    course_panels = [
        InlinePanel('handouts', label="讲义资料"),
        InlinePanel('group', label="时段信息"),
    ]

    edit_handler = TabbedInterface([
        ObjectList(content_panels, heading="基本信息"),
        ObjectList(course_panels, heading="讲义与时段信息"),
        ObjectList(Page.settings_panels, heading="设置", classname="settings"),
    ])

    parent_page_types = ['CourseIndexPage']
    subpage_types = ['news.NewsIndexPage']

    def clean(self):
        super().clean()
        self.slug = self.number

    class Meta:
        verbose_name = "课程"

class CourseHandout(Orderable):
    page = ParentalKey(CoursePage, on_delete=models.CASCADE, related_name='handouts')
    handout = models.ForeignKey(
        'wagtaildocs.Document', on_delete=models.CASCADE, related_name='+',
        verbose_name="讲义资料",
    )

    panels = [
        DocumentChooserPanel('handout'),
    ]

class CourseGroup(Orderable):
    page = ParentalKey(CoursePage, on_delete=models.CASCADE, related_name='group')
    info = models.CharField(max_length=40, verbose_name="时段描述")
    limit = models.IntegerField(default=0, verbose_name="人数上限")

    panels = [
        FieldPanel('info'),
        FieldPanel('limit'),
      #  InlinePanel('member'),
    ]

class GroupMember(models.Model):
    group = models.ForeignKey(CourseGroup, on_delete=models.CASCADE, related_name='member')
    number = models.CharField(max_length=15, verbose_name="学号")
    name = models.CharField(max_length=40, verbose_name="姓名")

    panels = [
        FieldPanel('number'),
        FieldPanel('name'),
    ]

course/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .models import CourseGroup, GroupMember, CoursePage

def index(request, group_id):
    group = get_object_or_404(CourseGroup, pk=group_id)
    member = GroupMember.objects.filter(group=group)
    errors = []
    if (member.count() > group.limit):
        errors = ["人数已经超限，后面的学生将无法参加实验，请换时间"]
    return render(request, 'course/group_index.html', {'members': member, 'group': group, 'errors': errors})

def joingroup(request, group_id):
    if request.user.username != 'Student':
        return render(request, 'course/group_index.html',
                {'errors':["必须是学生才可以加入组"]})
    group = get_object_or_404(CourseGroup, pk=group_id)
    page = CoursePage.objects.get(pk=group.page_id)
    errors = []
    for g in page.group.all():
        m = GroupMember.objects.filter(group=g,number=request.session['schoolid'])
        if (m.count() > 0):
            if (g == group):
                errors = ["你已经在这个组里面了"]
            else:
                errors = ["你在这个课的其他组里"]
    if errors == []:
        m = GroupMember(group=group)
        m.name = request.session['realname']
        m.number = request.session['schoolid']
        m.save()
    member = GroupMember.objects.filter(group=group)
    if (member.count() > group.limit):
        errors = ["人数已经超限，请调整到其它组"]
    return render(request, 'course/group_index.html',
            {'members': member,
             'errors': errors,
             'group': group})

def leavegroup(request, group_id):
    group = get_object_or_404(CourseGroup, pk=group_id)
    m = GroupMember.objects.filter(group=group,number=request.session['schoolid'])
    if (m.count() > 0):
        m.delete()
    member = GroupMember.objects.filter(group=group)
    return render(request, 'course/group_index.html',
            {'members': member, 'group': group})

course/templates/course/course_index_page.html
{% extends "nav.html" %}

{% load wagtailcore_tags %}

{% block subtitle %}{{ page.title }}{% endblock %}
{% block body_class %}article{% endblock %}
{% block mainblk %}
    <h1>{{ page.title }}</h1>
    {{ page.body|richtext }}

    {% for post in page.get_children %}
        <h2><a href="{% pageurl post %}">{{ post.title }}</a></h2>
    {% endfor %}

{% endblock %}

course/templates/course/course_page.html
{% extends "nav.html" %}

{% load wagtailcore_tags %}

{% block subtitle %}{{ page.title }}{% endblock %}
{% block body_class %}article{% endblock %}
{% block mainblk %}
<h4 class="text-center">{{ page.title }}</h4>
<ul class="nav nav-tabs">
    <li class="nav-item"><a class="nav-link active" href="#aaa" data-toggle="tab">课程基本情况</a></li>
    <li class="nav-item"><a class="nav-link" href="#bbb" data-toggle="tab">讲义资料</a></li>
    <li class="nav-item"><a class="nav-link" href="#ccc" data-toggle="tab">实验时段信息</a></li>
</ul>
<div class="tab-content" id="tabs">
    <div class="tab-pane active" id="aaa">
      <table width="100%" border="1" cellpadding="2" cellspacing="0" style="border-collapse: collapse">
         <tr><th width="15%">课程名称：</th><td width="80%">{{ page.name }}</td></tr>
         <tr><th>英文名称：</th><td>{{ page.ename }} </td></tr>
         <tr><th>课程编号：</th><td>{{ page.number }}</td></tr>
         <tr><th>主讲教师：</th><td>{{ page.teacher }}</td></tr>
         <tr><th>学分：</th><td>{{ page.unit }}</td></tr>
         <tr><th>学时：</th><td>{{ page.hours }}</td></tr>
         <tr><th>开课学期：</th><td> {{ page.terms }} </td></tr>
         <tr><th>课程大纲：</th><td>
        {{ page.body|richtext }}
        </td></tr>
      </table>
    </div>
    <div class="tab-pane" id="bbb">
        {% for item in page.handouts.all %}
        <a href="{{ item.handout.url }}">[{{ forloop.counter }}] {{ item.handout.title}}</a><br><br>
        {% endfor %}
    </div>
    <div class="tab-pane" id="ccc">
      <table width="100%" border="1" cellpadding="2" cellspacing="0" style="border-collapse: collapse">
          <tr><th width="60%">时段信息</th><th>人数上限</th><th>操作</th></tr>
        {% for item in page.group.all %}
        <tr><td>{{ item.info }}</td><td>{{ item.limit }}</td><td>
            {% if user.is_authenticated and user.username == 'Student' %}
              <a href="{% url 'course:joingroup' item.id %}">加入</a>
              <a href="{% url 'course:leavegroup' item.id %}">退出</a>
            {% endif %}
              <a href="{% url 'course:index' item.id %}">查看成员</a>
            </td> </tr>
        {% endfor %}
      </table>

    </div>
</div>
{% endblock %}

{% block sidebar %}
  <div class="card-header text-center">
     课程通知
  </div>
  <div class="card-body">
      {% for post in page.get_children.first.get_children.live.specific|dictsortreversed:"date"|slice:":5" %}
        <li><a href="{% pageurl post %}">{{ post.title }}</a></li>
    {% endfor %}
    {% if page.get_children.live.first.get_children.live.count > 5 %}
        <a href="{% pageurl page.get_children.live.first %}">更多通知</a>
    {% endif %}
    {% if page.teaid == request.session.schoolid %}
       <ul class="text-right">
       <a class="badge badge-warning" href="{% url 'wagtailadmin_pages:add_subpage' page.get_children.first.id %}">新建通知</a>
       </ul>
    {% endif %}
  </div>
  <div class="card-header text-center">
      全部课程
  </div>
  <div class="card-body">
    {% for post in page.get_siblings %}
      <li><a href="{% pageurl post %}">{{ post.title }}</a></li>
    {% endfor %}
  </div>
{% endblock %}

course/templates/course/group_index.html
{% extends "nav.html" %}

{% load wagtailcore_tags %}

{% block subtitle %}成员列表{% endblock %}
{% block body_class %}article{% endblock %}
{% block mainblk %}
    {% for err in errors %}
    <div class="alert alert-danger" role="alert">
        <h4>{{ err }}</h4>
    </div>
    {% endfor %}
    <h4 class="text-center">本时段成员列表</h4>
    <table class="table-sm table-hover table-bordered" width="100%">
     <tr><th width="10%">序号</th><th>姓名</th><th>学号</th>
    {% for member in members %}
    <tr><td> {{ forloop.counter }} <td>{{ member.name }}</td><td> {{ member.number }} </td></tr>
    {% endfor %}
    </table>

{% endblock %}
{% block sidebar %}
{% if group %}
<li><a href="{% pageurl group.page %}">回到课程</a></li>
{% endif %}
{% endblock %}