course/urls.py
from django.conf.urls import url
from . import views

app_name = 'course'
urlpatterns = [
    url(r'^join/(?P<group_id>[0-9]+)/$', views.joingroup, name='joingroup'),
    url(r'^leave/(?P<group_id>[0-9]+)/$', views.leavegroup, name='leavegroup'),
    url(r'(?P<group_id>[0-9]+)/$', views.index, name='index'),
]

meeting/urls.py
from django.conf.urls import url
from . import views

app_name = 'meeting'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^agenda/list/(?P<room_id>[0-9]+)/$', views.agenda_list, name='agenda_list'),
    url(r'^agenda/add/(?P<room_id>[0-9]+)/$', views.agenda_add, name='agenda_add'),
    url(r'^agenda/view/(?P<agenda_id>[0-9]+)/$', views.agenda_view, name='agenda_view'),
    url(r'^agenda/del/(?P<agenda_id>[0-9]+)/$', views.agenda_del, name='agenda_del'),
]

mywagtail/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from course import urls as course_urls
from meeting import urls as meeting_urls
from user import views as user_views

from search import views as search_views

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),
    url(r'^group/', include(course_urls)),
    url(r'^rooms/', include(meeting_urls)),
    url(r'^auth/', user_views.auth, name='auth'),
    url(r'^logout/', user_views.logout_view, name='logout_view'),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mywagtail/templates/base.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title> {% block title %}{% endblock %}</title>

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/mywagtail.css' %}">

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="bg-light {% block body_class %}{% endblock %}">

        {% block content %}{% endblock %}

        {# Global javascript #}
        <script type="text/javascript" src="{% static 'js/mywagtail.js' %}"></script>

        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>

mywagtail/templates/bootstrap.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block extra_css %}
    {% bootstrap_css %}

    {% if 'javascript_in_head'|bootstrap_setting %}
        <!-- Bootstrap JavaScript if it is in head -->
        {% bootstrap_javascript jquery=slim %}
    {% endif %}

    {% block bootstrap4_extra_head %}{% endblock %}
{% endblock %}

{% block extra_js %}
    {% if not 'javascript_in_head'|bootstrap_setting %}
        <!-- Bootstrap JavaScript if it is in body -->
        {% bootstrap_javascript jquery=slim %}
    {% endif %}
    {% block bootstrap4_extra_script %}{% endblock %}
{% endblock %}

mywagtail/templates/nav.html
{% extends "bootstrap.html" %}
{% load static %}

{% block title %}电子信息科学基础实验中心-{% block subtitle %}{% endblock %}{% endblock %}
{% block body_class %}homepage{% endblock %}
{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-dark mynav">
  <div class="d-lg-none align-top">
      <a class="navbar-brand" href="/">
        <img src="/media/logo-sm.png" alt="LOGO">
      </a>
      <h3 class="p-2 navbar-text text-light">电子信息科学<br>基础实验中心</h3>
  </div>
  <div class="d-none d-lg-block">
  <a id="logo" class="navbar-brand" href="/">
    <img src="/media/logo.png" alt="LOGO">
  </a>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <div class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <li class="p-2 navbar-text text-light"> 欢迎 {{ request.session.realname }}</li>
        <a class="p-2 text-light" href="/logout/">登出</a>
      {% else %}
      <a class="p-2 text-light" href="{% static 'html/login.html' %}">登录</a>
      {% endif %}
        <a class="p-2 text-light" href="/search/">搜索</a>
    </div>
  </div>
</nav>
<div class="container py-1 mb-2 border-bottom box-shadow">
  <nav class="nav nav-pills d-flex justify-content-between">
    <a class="p-2 text-muted" href="/">中心首页</a>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">中心简介</a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="/intro/1/">中心概况</a>
        <a class="dropdown-item" href="/intro/2/">组织结构</a>
        <a class="dropdown-item" href="/intro/3/">教学队伍</a>
        <a class="dropdown-item" href="/intro/4/">成果展示</a>
        <a class="dropdown-item" href="/intro/5/">对外交流</a>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">实验教学</a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="/course/">课程列表</a>
        <a class="dropdown-item" href="/intro/12/">中心实验室</a>
        <a class="dropdown-item" href="/intro/6/">课程体系</a>
        <a class="dropdown-item" href="/intro/7/">全部实验内容</a>
        <a class="dropdown-item" href="/intro/8/">电类课程</a>
        <a class="dropdown-item" href="/intro/9/">非电类课程</a>
        <a class="dropdown-item" href="/innovations/">创新园地</a>
      </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">教学资源</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="/static/html/kejian/">精品课件</a>
            <a class="dropdown-item" href="/static/html/datasheet/">元器件手册</a>
            <a class="dropdown-item" href="/static/html/download/">常用工具下载</a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">中心管理</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'meeting:index' %}">会议室预订</a>
            <a class="dropdown-item" href="/news/">全部新闻</a>
            <a class="dropdown-item" href="/book/">中心藏书</a>
            <a class="dropdown-item" href="/equip/">中心设备</a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">规章制度</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="/rules_c/">中心规章</a>
            <a class="dropdown-item" href="/rules_s/">院级规章</a>
            <a class="dropdown-item" href="/rules_u/">学校规章</a>
            <a class="dropdown-item" href="/laws/">国家法规</a>
        </div>
    </li>
    <a class="p-2 text-muted" href="/intro/100/">联系我们</a>
  </nav>
</div>
<main role="main" class="container">
  {% block jumbo %}
  <div class="row jumbotron p-3 p-md-5 text-dark rounded bg-white">
    <div class="col-md-8 mainblk">
      {% block mainblk %}
      {% endblock %}
    </div>
    <div class="col-md-4 sidebar">
      {% block sidebar %}
      {% endblock %}
    </div>
  </div>
  {% endblock %}
</main>
<footer class="card-footer text-muted text-center">
    <p>&copy; 北京大学电子信息科学基础实验中心 2017-2018</p>
</footer>
{% endblock %}